routes/web.php
<?php

use App\Http\Controllers\AnswerOptionController;
use App\Http\Controllers\Auth\WelcomeController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\ContentController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PanelHomeController;
use App\Http\Controllers\Patient\CourseController as PatientCourseController;
use App\Http\Controllers\Patient\ProfileController as PatientProfileController;
use App\Http\Controllers\Patient\TrainingController as PatientTrainingController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\PatientHomeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\RecipesController;
use App\Http\Controllers\RutasController;
use App\Http\Controllers\TrainingController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use Spatie\WelcomeNotification\WelcomesNewUsers;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function () {
    Route::view('/home', 'landing.patient.portal.index');
    Route::view('/cuestionario', 'landing.patient.cuestionario.index');
    Route::view('/cuestionario/2', 'landing.patient.cuestionario.index_2');

    Route::group(['middleware' => ['web', WelcomesNewUsers::class]], function () {
        Route::get('welcome/{user}', [WelcomeController::class, 'showWelcomeForm'])->name('welcome');
        Route::post('welcome/{user}', [WelcomeController::class, 'savePassword']);
    });

    Route::get('', HomeController::class)->name('index');

    Route::controller(ProfileController::class)->prefix('admin/profile')->as('admin.profile.')
        ->group(function () {
            Route::get('', 'index')->name('index');
            Route::match(['put', 'patch'], '', 'update')->name('update');
        });

    Route::middleware('can:is-administrator')->group(function () {
        Route::get('portal_panel', PanelHomeController::class)->name('portal_panel');

        Route::middleware(['verified'])->group(function () {
            Route::prefix('users')->name('users.')->group(function () {
                Route::apiResource('admins', UserController::class, ['except' => ['destroy']]);
                Route::apiResource('patients', PatientController::class, ['except' => ['destroy']])->withoutMiddleware(['auth', 'verified', 'can:is-administrator']);
            });

            Route::controller(CourseController::class)->prefix('trainings')->as('trainings.')
                ->group(function () {
                    Route::get('list_courses', 'index')->name('list_courses');
                });

            Route::controller(TrainingController::class)->prefix('trainings')->as('trainings.')
                ->group(function () {
                    Route::get('index', 'preview')->name('index');
                    Route::post('save', 'store')->name('store');
                    Route::get('list_modules', 'index')->name('list_modules');
                    Route::get('/module/edit/{id}', 'edit')->name('edit');
                    Route::post('/module/update/{id}', 'update')->name('update');
                    Route::post('/module/destroy/{id}', 'destroy')->name('destroy');
                });
            Route::controller(ContentController::class)->prefix('contents')->as('contents.')
                ->group(function () {
                    Route::get('index', 'preview')->name('index');
                    Route::post('save', 'store')->name('store');
                    Route::get('list_news', 'list')->name('list_news');
                    Route::get('details/{id}', 'show')->name('show');
                    Route::get('/new/edit/{id}', 'edit')->name('edit');
                    Route::post('/content/update/{id}', 'update')->name('update');
                    Route::post('/content/destroy/{id}', 'destroy')->name('destroy');
                });
            Route::controller(RecipesController::class)->prefix('contents')->as('contents.')
                ->group(function () {
                    route::Resource('recipes', RecipesController::class);
                });

            Route::controller(PostController::class)->prefix('blog')->as('blog.')
                ->group(function () {
                    Route::get('publications', 'list')->name('publications');
                    Route::post('publications', 'store')->name('publications.store');
                    Route::post('publications/update/{post}', 'update')->name('publications.update');
                    Route::post('publications/destroy/{post}', 'destroy')->name('publications.destroy');
                    Route::get('comments/chat', 'chat')->name('comments_chat');
                    Route::post('comments/post-admin', 'admin_post_store')->name('admin_post_store');
                });

            Route::controller(CommentController::class)->prefix('blog')->name('blog.')
                ->group(function () {
                    Route::get('comments', 'list')->name('comments');
                    Route::patch('comments/edit-post/{post}', 'user_update_status_post')->name('comments.post');
                });

            Route::controller(RutasController::class)->prefix('blog')->name('blog.')
                ->group(function () {
                    Route::get('interactions', 'blog_interactions')->name('interactions');
                });

            Route::controller(PostController::class)
                ->group(function () {
                    Route::get('publications', 'list')->name('publications');
                    Route::post('publications', 'store')->name('publications.store');
                    Route::post('publications/update/{post}', 'update')->name('publications.update');
                    Route::post('publications/destroy/{post}', 'destroy')->name('publications.destroy');
                });

            Route::controller(CommentController::class)
                ->group(function () {
                    Route::get('comments', 'list')->name('comments');
                });

            Route::controller(RutasController::class)
                ->group(function () {
                    Route::get('interactions', 'blog_interactions')->name('interactions');
                });
        });

        Route::controller(CourseController::class)->prefix('courses')->name('courses.')
            ->group(function () {
                Route::post('save', 'store')->name('store');
                Route::get('/edit/{course}', 'edit')->name('edit');
                Route::post('/update/{course}', 'update')->name('update');
                Route::post('/destroy/{course}', 'destroy')->name('destroy');
            });

        Route::prefix('questions')->name('questions.')->group(function () {
            route::Resource('questions', QuestionController::class)->names('questions');
            route::Resource('answers', AnswerOptionController::class)->names('answers');
        });
    });
    Route::middleware('can:is-patient')->group(function () {
        Route::get('tutorial/index', [PatientController::class, 'tutorial_patient'])->name('tutorial_patient.index');
        Route::get('index', PatientHomeController::class)->name('portal_patient.index');

        Route::controller(PatientProfileController::class)->prefix('perfil')->name('perfil.')
            ->group(function () {
                Route::get('', 'index')->name('index');
                Route::patch('', 'update')->name('update');
                Route::patch('/image', 'update_profile_image')->name('update_image');
            });

        Route::middleware(['verified'])->group(function () {
            Route::controller(PostController::class)
                ->group(function () {
                    Route::get('blog', 'patient_post_list')->name('content.patient_post_list');
                    Route::get('blog/post/{post}', 'patient_post_show')->name('blog_patient.show');
                    Route::post('blog/post/comment', 'patient_post_store')->name('blog_patient.store');
                    Route::get('post/like/{post}', 'patient_like')->name('blog.like');
                });

            Route::controller(PatientController::class)
                ->group(function () {
                    Route::get('cuestionario/2', 'cuestionario2_patient')->name('cuestionario2_patient.index');
                    Route::get('noticias', 'noticias_patient')->name('noticias_patient.index');
                });

            Route::controller(QuestionController::class)
                ->group(function () {
                    Route::get('cuestionario/{course}', 'index')->name('cuestionario_patient.index');
                });

            Route::controller(PatientTrainingController::class)->prefix('modules')->as('modules.')
                ->group(function () {
                    Route::get('', 'index')->name('index');
                    Route::get('view/{training}', 'verify')->name('verify');
                    Route::get('{patientTraining}', 'show')->name('show');
                });

            Route::controller(PatientCourseController::class)->prefix('modules')->as('modules.')
                ->group(function () {
                    Route::get('{patientTraining}/questionnaire/{course}', 'index')->name('questionnaire');
                    Route::post('{patientTraining}/questionnaire/{patientCourse}', 'questionnaire')->name('questionnaire.index');

app/Http/Controllers/Patient/CourseController.php
<?php

namespace App\Http\Controllers\Patient;

use App\Http\Controllers\Controller;
use App\Models\AnswerOption;
use App\Models\PatientCourse;
use App\Models\PatientTraining;
use App\Models\Question;
use App\Models\Trainings\Course;
use App\Services\Training\PatientCourseService;
use DragonCode\Support\Facades\Helpers\Str;
use Illuminate\Http\Request;

class CourseController extends Controller
{
    public function __construct()
    {
        $this->service = new PatientCourseService();
    }

    public function index(PatientTraining $patientTraining, Course $course)
    {
        $patientCourse = PatientCourse::firstOrCreate(
            [
                'patient_training_id' => $patientTraining->id,
                'course_id' => $course->id,
            ],
            ['start_date' => now()]
        );

        if (! is_null($patientCourse->end_date)) {
            abort(404);
        }

        $patientCourse->load([
            'course.questions.answers' => function ($query) {
                return $query->inRandomOrder();
            },
            'course.questions' => function ($query) {
                return $query->inRandomOrder();
            },
        ]);

        return view('landing.patient.cuestionario.index', compact(['patientTraining', 'patientCourse']));
    }

    public function questionnaire(Request $request, PatientTraining $patientTraining, PatientCourse $patientCourse)
    {
        if (! is_null($patientCourse->end_date)) {
            abort(404);
        }

        $answers = $this->storeResponses($patientCourse, $request);

        /** @var Collection */
        $courseQuestion = $patientCourse->course->questions;

        $correctQuestions = $courseQuestion->filter(function (Question $question) use ($answers) {
            /** @var Collection */
            $questionOptions = $question->answers;
            /** @var Collection */
            $correctOptions = $questionOptions->filter(fn ($value) => $value->is_correct == 1);
            /** @var Collection */
            $incorrectOptions = $questionOptions->filter(fn ($value) => $value->is_correct == 0);

            // Validando que todas las respuestas correctas de la pregunta hayan sido seleccionadas por el usuario
            $hasAllCorrectResponses = $correctOptions->every(function (AnswerOption $option) use ($answers) {
                return $answers->contains($option->id);
            });

            // Validando que ninguna de las respuestas incorrectas de la pregunta hayan sido seleccionadas por el usuario
            $doesNotHasAnyIncorrectResponses = $incorrectOptions->every(function (AnswerOption $option) use ($answers) {
                return ! $answers->contains($option->id);
            });

            // Se considera que la pregunta fue respondida correctamente sí, y
            // solo sí, el usuario seleccionó todas las respuestas correctas y
            // ninguna incorrecta
            return $doesNotHasAnyIncorrectResponses && $hasAllCorrectResponses;
        });

        $message = $correctQuestions->count();
        $puntaje = $message * 5;
        $total = $courseQuestion->count();

        $this->service->update($patientCourse, [
            'end_date' => now(),
            'points' => $puntaje,
        ]);

        $patientTraining->update([
            'points' => $puntaje + $patientTraining->points,
        ]);
        $patientTraining->patient->user->update([
            'points' => $patientTraining->patient->user->points + $puntaje,
        ]);

        return redirect()->route('modules.show', $patientTraining)->with('message', $total)->with('example', $message)->with('puntaje', $puntaje);
    }

    public function retry(PatientTraining $patientTraining, PatientCourse $patientCourse)
    {
        $patientTraining->update([
            'points' => $patientTraining->points - $patientCourse->points,
        ]);

        $patientTraining->patient->user->update([
            'points' => $patientTraining->patient->user->points - $patientCourse->points,
        ]);

        $course = $patientCourse->course_id;
        $patientCourse->delete();

        return redirect()->route('modules.questionnaire', ['patientTraining' => $patientTraining, 'course' => $course]);
    }

    public function storeResponses(PatientCourse $patientCourse, $request)
    {
        $answers = $request->collect()
            ->filter(fn ($value, $key) => Str::startsWith($key, 'answer_option_'))
            ->flatten();

        /** @var array */
        $challengeQuestionsIds = $patientCourse->course->questions->pluck('id');

        /** @var \Illuminate\Database\Eloquent\Collection<int, \App\Models\QuestionOption> */
        $challengeQuestionOptions = AnswerOption::whereIn('question_id', $challengeQuestionsIds)->get();

        /** @var \Illuminate\Database\Eloquent\Collection<int, \App\Models\QuestionOption> */
        $selectedOptions = AnswerOption::whereIn('id', $answers)
            ->get()
            ->intersect($challengeQuestionOptions);

        $patientCourse->responses()->sync($selectedOptions);

        return  $selectedOptions;
    }
}

app/Http/Controllers/Patient/ProfileController.php
<?php

namespace App\Http\Controllers\Patient;

use App\Http\Controllers\Controller;
use App\Http\Requests\Patient\ProfileUpdateRequest;
use App\Http\Requests\Patient\UpdateProfileImageRequest;
use App\Models\Patient;

class ProfileController extends Controller
{
    public function index()
    {
        /** @var \App\Models\User */
        $user = auth()->user();

        $user->load('patient');

        return view('landing.patient.profile.index');
    }

    public function edit(Patient $patient)
    {
        /** @var \App\Models\User */
        $user = auth()->user();

        $user->load('patient');

        return view('landing.patient.profile.index');
    }

    public function update(ProfileUpdateRequest $request)
    {
        /** @var \App\Models\User */
        $user = auth()->user();

        $user->update($request->all());
        $user->patient->update($request->all());
        session()->flash('success', 'Datos actualizados correctamente');

        return view('landing.patient.profile.index');
    }

    public function update_profile_image(UpdateProfileImageRequest $request)
    {
        $patient = auth()->user();
        if ($request->hasFile('profile_image') && $request->file('profile_image')->isValid()) {
            $patient->addMediaFromRequest('profile_image')->toMediaCollection('avatar');
        }
        session()->flash('success', 'Imagen actualizada correctamente');

        return redirect()->back();
    }
}

resources/views/landing/patient/cuestionario/connect.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body > 
<div id="page_connections" style="position: absolute; margin: 0 !important; padding: 0 !important; ">
<div class="row">
                    <div id="select_list_lebensbereiche">
                        <ul class="listado">
                            <li id="match1">Miedo a la soledad</li>
                            <li id="match2">Falta de confianza, desconfianza</li>
                            <li id="match3">Necesidad de aprobación</li>
                        </ul>
                    </div>
                    <div id="select_list_wirkdimensionen">
                        <ul class="listado">
                            <li id="answer1" class="text-right">Aceptación de nuestras cualidades y defectos como eres humanos</li>
                            <li id="answer2" class="text-right">Creer en nuestro valor y documentar las posibilidades</li>
                            <li id="answer3" class="text-right">Búsqueda de una compañía que sea grata y buen uso del tiempo libre</li>
                        </ul>
                    </div>
                    </div>
                </div>

</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsPlumb/2.15.0/js/jsplumb.min.js"></script>

<script>
    jQuery(document).ready(function() {
  var targetOption = {
    anchor: "LeftMiddle",
    maxConnections: 1,
    isSource: false,
    isTarget: true,
    reattach: true,
    endpoint: "Dot",
    connector: [ "Bezier", { curviness: 50 } ],
    setDragAllowedWhenFull: true
  };

  var sourceOption = {
    tolerance: "touch",
    anchor: "RightMiddle",
    maxConnections: 1,
    isSource: true,
    isTarget: false,
    reattach: true,
    endpoint: "Dot",
    connector: [ "Bezier", { curviness: 50 } ],
    setDragAllowedWhenFull: true
  };

  jsPlumb.importDefaults({
    ConnectionsDetachable: true,
    ReattachConnections: true,
    maxConnections: 1,
    Container: "page_connections"
  });

  var questionEndpoints = []; // 'source' and 'target' endpoints

  // "source" click handler
  jQuery("#select_list_lebensbereiche ul > li").click(function() {
    //remove existing start endpoint, if any:
    jsPlumb.deleteEndpoint(questionEndpoints[0]);
   
    // add a new one on the clicked element:
    questionEndpoints[0] = jsPlumb.addEndpoint(jQuery(this), sourceOption);
    connectEndpoints();
  });

  // "target" endpoint
  jQuery("#select_list_wirkdimensionen ul > li").click(function() {
    if (!questionEndpoints[0]) return; // don't respond if a source hasn't been selected
    // remove existing endpoint if any
    jsPlumb.deleteEndpoint(questionEndpoints[1]);
    //create a new one:
    questionEndpoints[1] = jsPlumb.addEndpoint(jQuery(this), targetOption);
    connectEndpoints();
  });

  var connectEndpoints = function() {
    jsPlumb.connect({
      source: questionEndpoints[0],
      target: questionEndpoints[1]
    });
  }
  
});


</script>



<style>
    .listado {
	 padding: 0;
	 margin-left: 150px;

	 float: left;
}
 .listado li {
	 list-style: none;
	 background-color: #ededed;
  border-radius: 20px;
  margin-bottom: 20px;
  padding: 10px;
}

 .jtk-connector path {
	 stroke: #38B9C3;
	 stroke-width: 5;

}
 .jtk-endpoint circle {
	 fill: #38B9C3;
}

 
</style>
</html>

resources/views/landing/patient/cuestionario/index.blade.php
@extends('landing.layouts.patient.app')
@section('content')
<script src="{{asset('landing/js/cuestionario/index.js')}}"></script>
<link rel="stylesheet" href="{{asset('landing/css/cuestionario/index.css')}}">
<div class="row-reverse">
    <div class="col">
        <label for="" class="h2 font-weight-bold mx-3"><b>Cuestionario |</b> {{ $patientCourse->course->name }}</label>
    </div>
    <div class="col">
        <label for="" class="h3 font-weight-bold mx-3">Bienvenido a la prueba</label>
        <hr>
    </div>
</div>
<ul>
    @foreach ($errors->all() as $error)
    <div class="alert alert-warning" role="alert">
        <span>{{ $error}}</span>
    </div>
    @endforeach
</ul>


<div class="row my-5 mt-4 ">
    @if(count($patientCourse->course->questions) <=0) <div class="container text-center">
        <div class="alert alert-warning" role="alert">
            <h3><i class="fa fa-exclamation-triangle mr-3"></i> No hay preguntas registradas</h3>
        </div>
</div>
@else
<div class="col-sm-10 m-auto r-100" id="item1">
    <form onsubmit="return checkSubmit();" id="challenge-form" action="{{ route('modules.questionnaire.index',["patientTraining"=>$patientTraining->id, "patientCourse"=>$patientCourse->id]) }}" method="post">
        @csrf
        @foreach ($patientCourse->course->questions as $question )
        <div class="card p-4 d-block row-reverse">
            <div class="col p-0  my-3">
                <label for="" class="h4 font-weight-bold"><b>{{ $loop->iteration }}. ¿{{ $question->label }}?</b></label>
            </div>
            <div class="row mx-auto mb-2">
                @foreach ($question->answers as $answer)
                <div @if(in_array($answer->getFirstMedia('banner_answer')?->extension, ['jpg','png','jpeg'])) class="col-md-3 d-flex justify-content-center" @else class="col-md-12" @endif >
                    <div class="row mx-auto p-0">
                        <div class="col-md-1 p-0 mt-3 d-flex justify-content-center align-items-center">
                            <div class="list-group fileinput fileinput-new text-center m-0" data-provides="fileinput">
                                @if($question->type == 'unique')
                                <label class="container">
                                    <input required class="form-check-input" type="radio" name="answer_option_{{$question->id}}" id="" value="{{$answer->id}}">
                                    <span class="checkmark"></span>
                                </label>
                                @else
                                <label class="container">
                                    <input data-required class="form-check-input" type="checkbox" name="answer_option_{{$question->id}}[]" id="" value="{{$answer->id}}">
                                    <span class="checkmark"></span>
                                </label>
                                @endif
                            </div>
                        </div>
                        <div class="col-md-10 p-0 mt-3">
                            <div class="row-reverse p-0 m-0 ">
                                <div class="col m-0 p-0">
                                    @if(in_array($answer->getFirstMedia('banner_answer')?->extension, ['jpg','png','jpeg']))
                                    <img style="border-radius:100%" width="200px" height="200px" src="{{ $answer->getFirstMediaUrl('banner_answer') }}" alt="">
                                    @elseif (in_array($answer->getFirstMedia('banner_answer')?->extension, ['ogg','mp3']))
                                    <div class="d-flex justify-content-center">
                                        <audio preload="auto" data-bs-toggle="tooltip" data-bs-placement="top" title="Audio de la respuesta" controls>
                                            <source src="{{$answer->getFirstMediaUrl('banner_answer')}}" type="audio/ogg">
                                            <source src="{{$answer->getFirstMediaUrl('banner_answer')}}" type="audio/mp3">
                                            Tu navegador no soporta audio HTML5.
                                        </audio>
                                    </div>
                                    @else
                                    <label for="" class="h5 font-weight-bold mt-4" style="float: left; color: #38B9C3"><b>{{
                                        $answer->label }}</b>
                                    </label>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
        </div>

        @endforeach
        @if (session()->has('status'))
        <script>
            $(document).ready(function() {
                $("#exampleModal").modal("show");
                window.location.href = "{{ route('index') }}";
            });
        </script>
        @endif
        <button type="submit" class="btn btn-primary mt-5 btn-block">Enviar</button>
    </form>
</div>
@endif
@endsection