routes/web.php
use App\Http\Controllers\Patient\CourseController as PatientCourseController;
use App\Http\Controllers\Patient\ProfileController as PatientProfileController;
use App\Http\Controllers\Patient\TrainingController as PatientTrainingController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\PatientHomeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\RecipesController;
use App\Http\Controllers\RutasController;
use App\Http\Controllers\TrainingController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use Spatie\WelcomeNotification\WelcomesNewUsers;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function () {
    Route::view('/home', 'landing.patient.portal.index');
    Route::view('/cuestionario', 'landing.patient.cuestionario.index');
    Route::view('/cuestionario/2', 'landing.patient.cuestionario.index_2');

    Route::group(['middleware' => ['web', WelcomesNewUsers::class]], function () {
        Route::get('welcome/{user}', [WelcomeController::class, 'showWelcomeForm'])->name('welcome');
        Route::post('welcome/{user}', [WelcomeController::class, 'savePassword']);
    });

    Route::get('', HomeController::class)->name('index');

    Route::controller(ProfileController::class)->prefix('admin/profile')->as('admin.profile.')
        ->group(function () {
            Route::get('', 'index')->name('index');
            Route::match(['put', 'patch'], '', 'update')->name('update');
        });

    Route::middleware('can:is-administrator')->group(function () {
        Route::get('portal_panel', PanelHomeController::class)->name('portal_panel');

        Route::middleware(['verified'])->group(function () {
            Route::prefix('users')->name('users.')->group(function () {
                Route::apiResource('admins', UserController::class, ['except' => ['destroy']]);
                Route::apiResource('patients', PatientController::class, ['except' => ['destroy']])->withoutMiddleware(['auth', 'verified', 'can:is-administrator']);
            });

            Route::controller(CourseController::class)->prefix('trainings')->as('trainings.')
                ->group(function () {
                    Route::get('list_courses', 'index')->name('list_courses');
                });

            Route::controller(TrainingController::class)->prefix('trainings')->as('trainings.')
                ->group(function () {
                    Route::get('index', 'preview')->name('index');
                    Route::post('save', 'store')->name('store');
                    Route::get('list_modules', 'index')->name('list_modules');
                    Route::get('/module/edit/{id}', 'edit')->name('edit');
                    Route::post('/module/update/{id}', 'update')->name('update');
                    Route::post('/module/destroy/{id}', 'destroy')->name('destroy');
                });
            Route::controller(ContentController::class)->prefix('contents')->as('contents.')
                ->group(function () {
                    Route::get('index', 'preview')->name('index');
                    Route::post('save', 'store')->name('store');
                    Route::get('list_news', 'list')->name('list_news');
                    Route::get('details/{id}', 'show')->name('show');
                    Route::get('/new/edit/{id}', 'edit')->name('edit');
                    Route::post('/content/update/{id}', 'update')->name('update');
                    Route::post('/content/destroy/{id}', 'destroy')->name('destroy');
                });
            Route::controller(RecipesController::class)->prefix('contents')->as('contents.')
                ->group(function () {
                    route::Resource('recipes', RecipesController::class);
                });

            Route::controller(PostController::class)->prefix('blog')->as('blog.')
                ->group(function () {
                    Route::get('publications', 'list')->name('publications');
                    Route::post('publications', 'store')->name('publications.store');
                    Route::post('publications/update/{post}', 'update')->name('publications.update');
                    Route::post('publications/destroy/{post}', 'destroy')->name('publications.destroy');
                    Route::get('comments/chat', 'chat')->name('comments_chat');
                    Route::post('comments/post-admin', 'admin_post_store')->name('admin_post_store');
                });

            Route::controller(CommentController::class)->prefix('blog')->name('blog.')
                ->group(function () {
                    Route::get('comments', 'list')->name('comments');
                    Route::patch('comments/edit-post/{post}', 'user_update_status_post')->name('comments.post');
                });

            Route::controller(RutasController::class)->prefix('blog')->name('blog.')
                ->group(function () {
                    Route::get('interactions', 'blog_interactions')->name('interactions');
                });

            Route::controller(PostController::class)
                ->group(function () {
                    Route::get('publications', 'list')->name('publications');
                    Route::post('publications', 'store')->name('publications.store');
                    Route::post('publications/update/{post}', 'update')->name('publications.update');
                    Route::post('publications/destroy/{post}', 'destroy')->name('publications.destroy');
                });

            Route::controller(CommentController::class)
                ->group(function () {
                    Route::get('comments', 'list')->name('comments');
                });

            Route::controller(RutasController::class)
                ->group(function () {
                    Route::get('interactions', 'blog_interactions')->name('interactions');
                });
        });

        Route::controller(CourseController::class)->prefix('courses')->name('courses.')
            ->group(function () {
                Route::post('save', 'store')->name('store');
                Route::get('/edit/{course}', 'edit')->name('edit');
                Route::post('/update/{course}', 'update')->name('update');
                Route::post('/destroy/{course}', 'destroy')->name('destroy');
            });

        Route::prefix('questions')->name('questions.')->group(function () {
            route::Resource('questions', QuestionController::class)->names('questions');
            route::Resource('answers', AnswerOptionController::class)->names('answers');
        });
    });
    Route::middleware('can:is-patient')->group(function () {
        Route::get('tutorial/index', [PatientController::class, 'tutorial_patient'])->name('tutorial_patient.index');
        Route::get('index', PatientHomeController::class)->name('portal_patient.index');

        Route::controller(PatientProfileController::class)->prefix('perfil')->name('perfil.')
            ->group(function () {
                Route::get('', 'index')->name('index');
                Route::patch('', 'update')->name('update');
                Route::patch('/image', 'update_profile_image')->name('update_image');
            });

        Route::middleware(['verified'])->group(function () {
            Route::controller(PostController::class)
                ->group(function () {
                    Route::get('blog', 'patient_post_list')->name('content.patient_post_list');
                    Route::get('blog/post/{post}', 'patient_post_show')->name('blog_patient.show');
                    Route::post('blog/post/comment', 'patient_post_store')->name('blog_patient.store');
                    Route::get('post/like/{post}', 'patient_like')->name('blog.like');
                });

            Route::controller(PatientController::class)
                ->group(function () {
                    Route::get('cuestionario/2', 'cuestionario2_patient')->name('cuestionario2_patient.index');
                    Route::get('noticias', 'noticias_patient')->name('noticias_patient.index');
                });

            Route::controller(QuestionController::class)
                ->group(function () {
                    Route::get('cuestionario/{course}', 'index')->name('cuestionario_patient.index');
                });

            Route::controller(PatientTrainingController::class)->prefix('modules')->as('modules.')
                ->group(function () {
                    Route::get('', 'index')->name('index');
                    Route::get('view/{training}', 'verify')->name('verify');
                    Route::get('{patientTraining}', 'show')->name('show');
                });

            Route::controller(PatientCourseController::class)->prefix('modules')->as('modules.')
                ->group(function () {
                    Route::get('{patientTraining}/questionnaire/{course}', 'index')->name('questionnaire');
                    Route::post('{patientTraining}/questionnaire/{patientCourse}', 'questionnaire')->name('questionnaire.index');
                    Route::get('{patientTraining}/questionnaire/{patientCourse}/retry', 'retry')->name('questionnaire.retry');
                });

            Route::controller(ContentController::class)
                ->group(function () {
                    Route::get('contents/list_news_patient', 'list_news_patient')->name('contents.list_news_patient');
                    Route::get('new/details/{id}', 'show')->name('content.show');

app/Models/Blog/Category.php
<?php

namespace App\Models\Blog;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @mixin IdeHelperCategory
 */
class Category extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'description',
    ];

    /**
     * Obtiene a los Posts asociados a la Categoría.
     *
     * @return HasMany
     */
    public function posts(): HasMany
    {
        return $this->hasMany(Post::class);
    }
}

app/Models/Blog/Comment.php
<?php

namespace App\Models\Blog;

use App\Models\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * @mixin IdeHelperComment
 */
class Comment extends Model
{
    protected $fillable = [
        'comment', 'active', 'post_id', 'user_id',
    ];

    use HasFactory;

    /**
     * @return [type]
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return [type]
     */
    public function post()
    {
        return $this->belongsTo(Post::class);
    }

    public function responses()
    {
        return $this->hasMany(Comment::class, 'parent_comment_id');
    }

    public function parentComment()
    {
        return $this->belongsTo(Comment::class, 'parent_comment_id');
    }
}

app/Models/Blog/LikePost.php
<?php

namespace App\Models\Blog;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * @mixin IdeHelperLikePost
 */
class LikePost extends Model
{
    use HasFactory;
}

app/Models/Blog/Post.php
<?php

namespace App\Models\Blog;

use App\Models\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

/**
 * @mixin IdeHelperPost
 */
class Post extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia;

    protected $fillable = [
        'title', 'body', 'author_id', 'publication_starts_at', 'publication_ends_at',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'publication_starts_at' => 'date:d-m-Y',
        'publication_ends_at' => 'date:d-m-Y',
    ];

    public function author()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Obtiene a los Comentarios asociadas al Post.
     *
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class)
        ->orderByDesc('created_at');
    }

    public function likes()
    {
        return $this->hasMany(LikePost::class);
    }

    public function categoy()
    {
        return $this->belongsTo(Category::class);
    }

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('file')
            ->useFallbackUrl('/img/no_banner.jpg')
            ->singleFile();
    }
}

resources/views/panel/blog/publications/create.blade.php
<button data-bs-toggle="modal" data-bs-target="#crearpublicacion" class="btn btn-primary col-2">Crear Publicacion</button>
<!-- Modal -->
<div class="modal fade" id="crearpublicacion" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-dark">
                <h5 class="modal-title text-white" id="exampleModalLabel">Crear Publicacion</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
                <form action="{{route('blog.publications.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    @include('panel.blog.publications.form')
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                        <button type="submit" class="btn btn-primary">Crear Publicacion</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/panel/blog/publications/edit.blade.php
<!-- Button trigger modal -->

  <button type="button" class="btn btn-primary d-inline-block" data-bs-toggle="modal" data-bs-target="#editar{{ $post->id }}">
    <i class="fa fa-edit"></i>
  </button>
<!-- Modal -->
<div class="modal fade" id="editar{{ $post->id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-dark">
        <h5 class="modal-title text-white" id="exampleModalLabel">Editar Publicacion</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="">
        <div class="row g-4">
          <div class="col-12">
            <div class="card">
              <img data-bs-toggle="tooltip" data-bs-placement="top" title="Imagen de la publicación" src="{{$post->getFirstMediaUrl('file')}}" class="" alt="...">
              <div class="card-body">
                <h5 class="card-title mb-3">{{$post->title}}</h5>
                <form action="{{ route('blog.publications.update',[$post]) }}" method="post" enctype="multipart/form-data">
                  @csrf
                  @include('panel.blog.publications.form')
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

resources/views/panel/blog/publications/form.blade.php
<div class="row">
    <div class="col-sm-6 ">
        <label for="">Titulo</label>
        <input required value="{{ isset($post->title) ? $post->title : '' }}" name="title"
            class="form-control" type="text" placeholder="Titulo">
    </div>
    <div class="col-sm-6 ">
        <label for="">Imagen o video</label>
        <input accept="image/*" data-bs-toggle="tooltip" data-bs-placement="top" title="Cargar imagen" required  name="file" id="file"
            class="form-control" type="file" placeholder="Titulo">
    </div>
    <div class="col-sm-12 ">
        <label for="">Descripción</label>
        <textarea class="form-control" required name="body" placeholder="Digite el nombre de la publicación..." cols="5"rows="2">{{ isset($post->body) ? $post->body : '' }}</textarea>
    </div>
    <div class="col-sm-6 ">
        <label class="form-label" for="">Fecha de publicacion</label>
        <input min="{{now()->format('Y-m-d')}}" required value="{{ isset($post->publication_starts_at) ? $post->publication_starts_at->format('Y-m-d') : '' }}"
            name="publication_starts_at" class="form-control" type="date" placeholder="Titulo">
    </div>
    <div class="col-sm-6 ">
        <label class="form-label" for="">Fecha de caducidad</label>
        <input min="{{now()->format('Y-m-d')}}" required value="{{ isset($post->publication_ends_at) ? $post->publication_ends_at->format('Y-m-d') : '' }}"
            name="publication_ends_at" class="form-control" type="date" placeholder="Titulo">
    </div>
</div>
<script>
    CKEDITOR.replace( 'id{{isset($post->id) ? $post->id : ''}}');
</script>

resources/views/panel/blog/publications/publications.blade.php
@extends('panel.layouts.app')
@section('content')
<div class="row-reverse">
    <div class="col my-5">
        <div class="row">
            <div class="col">
                <label for="" class="h3">Publicaciones</label>
            </div>
            @if(session('success'))
            <div class="alert alert-success">{{session('success')}}</div>
            @endif
            @if(session('message'))
            <div class="alert alert-success">{{session('message')}}</div>
            @endif
            @if(session('error'))
            <div class="alert alert-danger">{{session('error')}}</div>
            @endif
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            @include('panel.blog.publications.create')
        </div>

    </div>
    <div class="col">
     <div class="table-responsive">
        <table id="example" class="table-sm table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th scope="col">Titulo</th>
                    <th scope="col">Contenido</th>
                    <th scope="col">Autor</th>
                    <th scope="col">Fecha de publicacion</th>
                    <th scope="col">Fecha de caducidad</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach($posts as $post)
                <tr>
                    <td>{{Str::limit($post->title,10)}}</td>
                    <td>{{Str::limit($post->body,15)}}</td>
                    <td>{{$post->author->name}}</td>
                    <td>{{$post->publication_starts_at->format('d/m/Y')}}</td>
                    <td>{{$post->publication_ends_at->format('d/m/Y')}}</td>
                    <td>
                        <form class="d-inline-block" action="{{route('blog.publications.destroy',[$post])}}" method="post">
                            @csrf
                            <button data-bs-toggle="tooltip" data-bs-placement="top" title="Eliminar publicación" onclick="return confirm('¿Desea Eliminar Está Publicación?')" type="submit" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                          </form>
                        @include('panel.blog.publications.edit')
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
     </div>
    </div>
</div>
@endsection