routes/web.php
<?php

use App\Http\Controllers\AnswerOptionController;
use App\Http\Controllers\Auth\WelcomeController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\ContentController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PanelHomeController;
use App\Http\Controllers\Patient\CourseController as PatientCourseController;
use App\Http\Controllers\Patient\ProfileController as PatientProfileController;
use App\Http\Controllers\Patient\TrainingController as PatientTrainingController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\PatientHomeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\RecipesController;
use App\Http\Controllers\RutasController;
use App\Http\Controllers\TrainingController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use Spatie\WelcomeNotification\WelcomesNewUsers;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function () {
    Route::view('/home', 'landing.patient.portal.index');
    Route::view('/cuestionario', 'landing.patient.cuestionario.index');
    Route::view('/cuestionario/2', 'landing.patient.cuestionario.index_2');

    Route::group(['middleware' => ['web', WelcomesNewUsers::class]], function () {
        Route::get('welcome/{user}', [WelcomeController::class, 'showWelcomeForm'])->name('welcome');
        Route::post('welcome/{user}', [WelcomeController::class, 'savePassword']);
    });

    Route::get('', HomeController::class)->name('index');

    Route::controller(ProfileController::class)->prefix('admin/profile')->as('admin.profile.')
        ->group(function () {
            Route::get('', 'index')->name('index');
            Route::match(['put', 'patch'], '', 'update')->name('update');
        });

    Route::middleware('can:is-administrator')->group(function () {
        Route::get('portal_panel', PanelHomeController::class)->name('portal_panel');

        Route::middleware(['verified'])->group(function () {
            Route::prefix('users')->name('users.')->group(function () {
                Route::apiResource('admins', UserController::class, ['except' => ['destroy']]);
                Route::apiResource('patients', PatientController::class, ['except' => ['destroy']])->withoutMiddleware(['auth', 'verified', 'can:is-administrator']);
            });

            Route::controller(CourseController::class)->prefix('trainings')->as('trainings.')
                ->group(function () {
                    Route::get('list_courses', 'index')->name('list_courses');
                });

            Route::controller(TrainingController::class)->prefix('trainings')->as('trainings.')
                ->group(function () {
                    Route::get('index', 'preview')->name('index');
                    Route::post('save', 'store')->name('store');
                    Route::get('list_modules', 'index')->name('list_modules');
                    Route::get('/module/edit/{id}', 'edit')->name('edit');
                    Route::post('/module/update/{id}', 'update')->name('update');
                    Route::post('/module/destroy/{id}', 'destroy')->name('destroy');
                });
            Route::controller(ContentController::class)->prefix('contents')->as('contents.')
                ->group(function () {
                    Route::get('index', 'preview')->name('index');
                    Route::post('save', 'store')->name('store');
                    Route::get('list_news', 'list')->name('list_news');
                    Route::get('details/{id}', 'show')->name('show');
                    Route::get('/new/edit/{id}', 'edit')->name('edit');
                    Route::post('/content/update/{id}', 'update')->name('update');
                    Route::post('/content/destroy/{id}', 'destroy')->name('destroy');
                });
            Route::controller(RecipesController::class)->prefix('contents')->as('contents.')
                ->group(function () {
                    route::Resource('recipes', RecipesController::class);
                });

            Route::controller(PostController::class)->prefix('blog')->as('blog.')
                ->group(function () {
                    Route::get('publications', 'list')->name('publications');
                    Route::post('publications', 'store')->name('publications.store');
                    Route::post('publications/update/{post}', 'update')->name('publications.update');
                    Route::post('publications/destroy/{post}', 'destroy')->name('publications.destroy');
                    Route::get('comments/chat', 'chat')->name('comments_chat');
                    Route::post('comments/post-admin', 'admin_post_store')->name('admin_post_store');
                });

            Route::controller(CommentController::class)->prefix('blog')->name('blog.')
                ->group(function () {
                    Route::get('comments', 'list')->name('comments');
                    Route::patch('comments/edit-post/{post}', 'user_update_status_post')->name('comments.post');
                });

            Route::controller(RutasController::class)->prefix('blog')->name('blog.')
                ->group(function () {
                    Route::get('interactions', 'blog_interactions')->name('interactions');
                });

            Route::controller(PostController::class)
                ->group(function () {
                    Route::get('publications', 'list')->name('publications');
                    Route::post('publications', 'store')->name('publications.store');
                    Route::post('publications/update/{post}', 'update')->name('publications.update');
                    Route::post('publications/destroy/{post}', 'destroy')->name('publications.destroy');
                });

            Route::controller(CommentController::class)
                ->group(function () {
                    Route::get('comments', 'list')->name('comments');
                });

            Route::controller(RutasController::class)
                ->group(function () {
                    Route::get('interactions', 'blog_interactions')->name('interactions');
                });
        });

        Route::controller(CourseController::class)->prefix('courses')->name('courses.')
            ->group(function () {
                Route::post('save', 'store')->name('store');
                Route::get('/edit/{course}', 'edit')->name('edit');
                Route::post('/update/{course}', 'update')->name('update');
                Route::post('/destroy/{course}', 'destroy')->name('destroy');
            });

        Route::prefix('questions')->name('questions.')->group(function () {
            route::Resource('questions', QuestionController::class)->names('questions');
            route::Resource('answers', AnswerOptionController::class)->names('answers');
        });
    });
    Route::middleware('can:is-patient')->group(function () {
        Route::get('tutorial/index', [PatientController::class, 'tutorial_patient'])->name('tutorial_patient.index');
        Route::get('index', PatientHomeController::class)->name('portal_patient.index');

        Route::controller(PatientProfileController::class)->prefix('perfil')->name('perfil.')
            ->group(function () {
                Route::get('', 'index')->name('index');
                Route::patch('', 'update')->name('update');
                Route::patch('/image', 'update_profile_image')->name('update_image');
            });

        Route::middleware(['verified'])->group(function () {
            Route::controller(PostController::class)
                ->group(function () {
                    Route::get('blog', 'patient_post_list')->name('content.patient_post_list');
                    Route::get('blog/post/{post}', 'patient_post_show')->name('blog_patient.show');
                    Route::post('blog/post/comment', 'patient_post_store')->name('blog_patient.store');
                    Route::get('post/like/{post}', 'patient_like')->name('blog.like');
                });

            Route::controller(PatientController::class)
                ->group(function () {
                    Route::get('cuestionario/2', 'cuestionario2_patient')->name('cuestionario2_patient.index');
                    Route::get('noticias', 'noticias_patient')->name('noticias_patient.index');
                });

            Route::controller(QuestionController::class)
                ->group(function () {
                    Route::get('cuestionario/{course}', 'index')->name('cuestionario_patient.index');
                });

            Route::controller(PatientTrainingController::class)->prefix('modules')->as('modules.')
                ->group(function () {
                    Route::get('', 'index')->name('index');
                    Route::get('view/{training}', 'verify')->name('verify');
                    Route::get('{patientTraining}', 'show')->name('show');
                });

            Route::controller(PatientCourseController::class)->prefix('modules')->as('modules.')
                ->group(function () {
                    Route::get('{patientTraining}/questionnaire/{course}', 'index')->name('questionnaire');
                    Route::post('{patientTraining}/questionnaire/{patientCourse}', 'questionnaire')->name('questionnaire.index');

app/Models/Trainings/Course.php
<?php

namespace App\Models\Trainings;

use App\Models\PatientCourse;
use App\Models\Question;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

/**
 * @mixin IdeHelperCourse
 */
class Course extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'training_id',
        'name',
        'description',
        'status',
        'URL',
    ];

    /**
     * Retrieves the training associated to the model.
     *
     * @return BelongsTo
     */
    public function training(): BelongsTo
    {
        return $this->belongsTo(Training::class);
    }

    /**
     * Retrieves the cuestions associated to the model.
     *
     * @return HasMany
     */
    public function questions()
    {
        return $this->hasMany(Question::class);
    }

    public function patienCourse()
    {
        return $this->hasMany(PatientCourse::class);
    }

    /**
     * Strip HTML and PHP tags from the description column.
     *
     * @param  string  $value
     * @return \Illuminate\Database\Eloquent\Casts\Attribute
     */
    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('banner')
            ->useFallbackUrl('/img/no_banner.jpg')
            ->singleFile();

        $this->addMediaCollection('media')
            ->singleFile();
    }
}

app/Models/Trainings/DocumentTraining.php
<?php

namespace App\Models\Trainings;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * @mixin IdeHelperDocumentTraining
 */
class DocumentTraining extends Model
{
    use HasFactory;

    protected $table = 'bc_capacitacion_documento';

    protected $primaryKey = 'id_capacitacion_documento';
}

app/Models/Trainings/TrainingUser.php
<?php

namespace App\Models\Trainings;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * @mixin IdeHelperTrainingUser
 */
class TrainingUser extends Model
{
    use HasFactory;

    protected $table = 'bc_capacitacion_user';

    protected $primaryKey = 'id_capacitacion_user';
}

app/Http/Controllers/Patient/TrainingController.php
<?php

namespace App\Http\Controllers\Patient;

use App\Http\Controllers\Controller;
use App\Models\PatientTraining;
use App\Models\Trainings\Training;
use App\Services\Training\PatientTrainingService;

class TrainingController extends Controller
{
    /** @var PatientTrainingService */
    private $service;

    /**
     * Init the controller.
     *
     * @return void
     */
    public function __construct()
    {
        $this->service = new PatientTrainingService();
    }

    /**
     * @return [type]
     */
    public function index()
    {
        $trainings = Training::orderBy('created_at', 'desc')->paginate(2);
        // $trainings->load('courses.answer');
        $trainings->load(['courses' => function ($query) {
            $query->where('status', 'Publicado');
        }]);

        return view('landing.patient.retos.trainings', compact('trainings'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(PatientTraining $patientTraining)
    {
        $patientTraining->load(['training.courses', 'courses.course'])->loadSum('courses', 'points');
        $trainingCourses = $patientTraining->training->courses;

        return view('landing.patient.retos.trainings_details', compact('patientTraining', 'trainingCourses'));
    }

    public function verify(Training $training)
    {
        $patientTraining = PatientTraining::where('patient_id', auth()->user()->patient->id)
            ->where('training_id', $training->id)
            ->first();

        if (is_null($patientTraining)) {
            $input = [
                'training_id' => $training->id,
                'patient_id' => auth()->user()->patient->id,
                'start_date' => now(),
                'points' => 0,
            ];
            $patientTraining = $this->service->store($input);
        }

        return redirect()->route('modules.show', ['patientTraining' => $patientTraining]);
    }
}

app/Http/Controllers/TrainingController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Training\StoreRequest;
use App\Http\Requests\Training\UpdateRequest;
use App\Models\Trainings\Course;
use App\Models\Trainings\Training;
use App\Services\Training\TrainingService;

class TrainingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function preview()
    {
        $trainings = Training::withCount('courses')->orderBy('created_at', 'desc')->take(3)->get();
        $courses = Course::orderBy('created_at', 'desc')->take(3)->get();

        return view('panel.trainings.index', compact('trainings', 'courses'));
    }

    public function index()
    {
        $trainings = Training::orderBy('created_at', 'desc')->get();

        return view('panel.trainings.list_modules', compact('trainings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        $training = TrainingService::store($request);
        $training->addMediaFromRequest('mod_banner')->toMediaCollection('banner');
        session()->flash('success', 'Modulo creado correctamente');

        return redirect()->route('trainings.list_modules');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $training = Training::find($id);

        return view('landing.patient.retos.trainings_details', compact('training'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $training = Training::findOrFail($id);

        return view('panel.trainings.modules_edit', compact('training'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        $training = Training::findOrFail($id);
        $training = TrainingService::update($request, $training);
        session()->flash('success', 'Modulo actualizado correctamente');

        return redirect()->route('trainings.list_modules');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $training = Training::findOrFail($id);
        $training->delete();
        session()->flash('success', 'Modulo eliminado correctamente');

        return redirect()->route('trainings.list_modules');
    }
}

resources/views/panel/trainings/index.blade.php
{{-- @extends('panel.layouts.app')
@section('content')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<div class="row">
    <div class="col">
        <div class="card card-body">
            <div class="row-reverse">
                <div class="col d-flex justify-content-center my-3">
                    <div class="row">
                        <div class="col d-flex justify-content-center align-items-center">
                            <label for="" class="h3">Modulos</label>
                        </div>
                        <div class="col d-flex justify-content-center align-items-center">
                            <a href="javascript:;" style="cursor:pointer" title="Agregar Modulo" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                <i class="fas fa-plus-circle fa-2x mb-1" style="color: #312783 "></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col d-flex justify-content-center ">
                        <a href="{{ route('trainings.list_modules') }}" class="h5" style="text-decoration-line: underline">Ver Mas</a>
                    </div>
                </div>
                <div class="col ">
                    <div class="row-reverse ">
                        @foreach($trainings as $training)
                        <div class="col-10 mx-auto card_list mb-3">
                            <div class="card ">
                                <div class="img_card p-3">
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="row-reverse">
                                                <div class="col">

                                                    <p>{{$training->name}}</p>
                                                </div>
                                                <div class="col">
                                                    <p class="fa-sm">
                                                        {{$training->description}}
                                                    </p>
                                                </div>
                                                <div class="col">
                                                    <p>Numero de cursos: {{$training->courses_count}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card card-body">
            <div class="row-reverse">
                <div class="col d-flex justify-content-center my-3">
                    <div class="row">
                        <div class="col d-flex justify-content-center align-items-center">
                            <label for="" class="h3">Cursos</label>
                        </div>
                        <div class="col d-flex justify-content-center align-items-center">
                            <a href="javascript:;" style="cursor:pointer" title="Agregar Modulo" data-bs-toggle="modal" data-bs-target="#exampleModal2">
                                @include('panel.trainings.course_create')
                                <i class="fas fa-plus-circle fa-2x mb-1" style="color: #312783 "></i>
                            </a>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col d-flex justify-content-center ">
                        <a href="{{ route('trainings.list_courses') }}" class="h5" style="text-decoration-line: underline">Ver Mas</a>
                    </div>
                </div>
                <div class="col ">
                    <div class="row-reverse ">
                        @foreach($courses as $course)
                        <div class="col-10 mx-auto card_list mb-3 d-flex">
                            <div class="card ">
                                <div class="img_card p-3">
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="row-reverse">
                                                <div class="col">
                                                    <p>{{$course->name}}</p>
                                                </div>
                                                <div class="col">
                                                    <p class="fa-sm">{{$course->description}}
                                                    </p>
                                                </div>
                                                <div class="col">
                                                    <p>Modulo: {{ $course->training->name }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .card_list {
        min-height: 20vh;
        max-height: 20vh;
        background: #F5F5F5;
        border-radius: 20px;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .img_card {
        min-height: 15vh;
        max-height: 15vh;
        max-width: 30vw;
        min-width: 30vw;
        border-radius: 20px;
        cursor: pointer;
        overflow: hidden;
    }

    .img_card:hover {
        border-color: #312783;
        border-style: solid;
        border-width: 2px;
    }

    .img_curso {
        width: 100px;
        height: 100px;
        background: gray;
        border-radius: 60px;
    }
</style>
@endsection --}}

resources/views/panel/trainings/list_modules.blade.php
@extends('panel.layouts.app')
@section('content')
<div class="row-reverse">
    <div class="col my-5">
        <div class="row">
            <div class="col">
                <label for="" class="h3">Modulos</label>
            </div>
            <div class="col d-flex justify-content-end">
                <a href="javascript:;" class="btn btn-primary" title="Agregar Modulo" data-bs-toggle="modal" data-bs-target="#exampleModal">Agregar
                    Modulo</a>
            </div>
            @if(session('success'))
            <div class="alert alert-success">{{session('success')}}</div>
            @endif
            @if(session('message'))
            <div class="alert alert-info">{{session('message')}}</div>
            @endif
            @if(session('error'))
            <div class="alert alert-danger">{{session('error')}}</div>
            @endif
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
        </div>
    </div>
    <div class="col table-responsive">
        <table id="example" class="table table-sm  table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th scope="col">Titulo</th>
                    <th scope="col">Descripción</th>
                    <th scope="col">Fecha de creación</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach($trainings as $training)
                <tr>
                    <td>{{$training->name}}</td>
                    <td>{{Str::limit($training->description, 40)}}</td>
                    <td>{{$training->created_at}}</td>
                    <td>
                        <a data-bs-toggle="tooltip" data-bs-placement="top" title="Editar modulo" href="{{route('trainings.edit',[$training])}}" class="btn btn-primary "><i class="fas fa-edit"></i></a>
                        <form class="d-inline-block" action="{{route('trainings.destroy',[$training])}}" method="post">
                            @csrf
                            <button data-bs-toggle="tooltip" data-bs-placement="top" title="Eliminar modulo" onclick="return confirm('¿Desea eliminar este modulo?')" type="submit" class="btn btn-danger d-inline-block"><i class="fas fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
                @endforeach

            </tbody>
        </table>
    </div>
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-dark">
                <h5 class="modal-title text-white" id="exampleModalLabel">Crear modulos</h5>
                <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body py-3">
                <div class="row">
                    <div class="col">
                        <form action="{{route('trainings.store')}}" method="post" id="register" enctype="multipart/form-data" required>
                            @csrf
                            <div class="row-reverse">
                                <div class="row">
                                    <div class="col mb-3">
                                        <label for="">Nombre</label>
                                        <input required type="text" name="name" id="" class="form-control" placeholder="Titulo del modulo" required>
                                    </div>
                                    <div class="col mb-3">
                                        <label for="">Patología</label>
                                        <select required name="type" id="" class="form-control" required>
                                            <option value="" disabled selected>Tipo</option>
                                            <option value="General">General</option>
                                            <option value="General">Patologia</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col mb-3">
                                    <div class="row">
                                        <div class="col">
                                            <label for="">Descripción</label>
                                            <textarea required name="description" id="" cols="10" rows="2" class="form-control" placeholder="Descripcion del modulo" required></textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">

                                    <div class="col mb-3">
                                        <div class="row">
                                            <div class="col">
                                                <label for="">Adjuntar documento de introducción</label>
                                                <input accept=".pdf" data-bs-toggle="tooltip" data-bs-placement="top" title="Cargar documento" required type="file" name="document" id="" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="">Adjuntar Imagen del modulo</label>
                                        <input accept="image/*" data-bs-toggle="tooltip" data-bs-placement="top" title="Cargar imagen" required type="file" name="mod_banner" id="mod_banner" class="form-control">
                                    </div>
                                </div>
                                <div class="modal-footer d-flex justify-content-center ">
                                    <button data-bs-toggle="tooltip" data-bs-placement="top" title="Crear modulo" type="submit" class="btn w-30 bg-gradient-primary">Agregar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection